### ISSUE TITLE
Deploy project on Netflify

### ISSUE THREAD

**Issue by przemekkwiatkowski** [przemekkwiatkowski/react-pwa-benchmark#4]
https://react-pwa-benchmark.netlify.com

@simplypixi  czy konfigurujemy coś co by się przydało dodając plik `netlify.toml`?

**Comment by simplypixi** [comment]
@przemekkwiatkowski co masz na mysli? Mgłbyś rozwinąć swoją myśl?

**Comment by przemekkwiatkowski** [comment]
@simplypixi czy jak robimy w firmie deploy na Netlify to dodajemy i konfigurujemy od razu plik`netlify.toml`? i jeśli tak - to czy warto byłoby tu to zrobić, żeby przećwiczyć

**Comment by simplypixi** [comment]
@przemekkwiatkowski To zależy od potrzeb. W Twoim wypadku sprawa wygląda tak - robisz SPA (PWA). W związku z tym musisz dodać przekierowanie wszystkich adresów na `index.html`, czyli stworzyć `netlify.toml`, który to przekierowanie zawiera.
Spróbuj sobie wejść teraz na adres, który wrzuciłeś wyżej - rzuci 404. ;)

Pomocne źródło: https://www.netlify.com/docs/netlify-toml-reference/
